logging:
  level:
    ROOT: INFO
    org:
      springframework:
        beans:
          factory:
            support: INFO
        cloud: INFO
        amqp: INFO
        integration:
          channel: INFO
          amqp: INFO


hystrix:
  command:
    default:
      execution:
#        timeout:
#          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 10000
#            interruptOnTimeout: false
